### PR TITLE
Add channel/stream search function

### PR DESCRIPTION
**Pull request by andyklimczak**
Hey, love this library, thanks for creating it

The search channels api endpoint solves a use case for me, and I wanted to implement it inside this

Thanks!

### CODE REVIEW

**Comment by Stateford** [comment]
Nice, I didn't realize this was part of the twitch API. If you add a search games function to the PR I will merge them.

**Comment by Stateford** [comment]
You can update the README if you want as well, or I can do it after the PR.

**Comment by andyklimczak** [comment]
Updated, added searchGames and updated the readme

**Comment by Stateford** [comment]
Thanks. If there's anything else you think should be added make an issue or PR.

**Pull request merged**
